runtime : review print info AND add command to access main runtime binary AND remove npm-config command

diff --git a/aistack b/aistack
--- a/aistack
+++ b/aistack
@@ -111,13 +111,13 @@ Options:
     cpa key delete <key>                 Remove an API key from CLIProxyAPI configuration.
     cpa model list                       List all available LLM models from CLIProxyAPI endpoint.
     ----
-    npm-config set <key> <value>         Set a npm configuration for the internal nodejs.
+    nvm|npm|npx|pip|pipx|uv [<command>]           Execute nvm, npm, npx, pip, pipx, or uv command using the internal nodejs or python runtime from aistack. (i.e: aistack npm install -g typescript)
     ----
     app killport <port>                  Kill process running on a specific port.
     ----
     bmad <install|uninstall>            Install/Uninstall bmad cli.
-    bmad register <shell>|vs          Register bmad PATH into shell env PATH ("bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs")
-    bmad unregister <shell>|vs        Unregister bmad PATH into shell env PATH ("bash", "zsh", "fish" or "all") or into VS Code integrated terminal env PATH ("vs")
+    bmad register <shell>|vs            Register bmad cli PATH into shell env PATH ("bash", "zsh" or "fish") or into VS Code integrated terminal env PATH ("vs")
+    bmad unregister <shell>|vs          Unregister bmad cli PATH into shell env PATH ("bash", "zsh", "fish" or "all") or into VS Code integrated terminal env PATH ("vs")
     ----
 EOF
 }
@@ -154,30 +154,49 @@ main() {
         uninstall)
             aistack_uninstall
             ;;
-        npm-config)
+        npm|npx)
             if ! check_requirements "nodejs"; then echo " -- ERROR : nodejs missing, launch aistack init"; exit 1; fi;
-            local sub_command="$1"
-            shift
-            case "$sub_command" in
-                set)
-                    local key="$1"
-                    shift
-                    local value="$1"
-                    shift
-                    if [ -z "$key" ]; then
-                        echo " -- ERROR : Missing key for npm-config set"
-                        usage
-                        exit 1
-                    fi
-                    echo "Setting npm config: $key = $value"
-                    PATH="${AISTACK_NODEJS_BIN_PATH}:${PATH}" npm config set "$key" "$value" -g
-                    ;;
-                *)
-                    echo "Error: Unknown command $sub_command for npm-config"
-                    usage
-                    exit 1
-                    ;;
-            esac
+            if [ "$AISTACK_INTERNAL_NODEJS_RUNTIME_AVAILABLE" = "true" ]; then
+                PATH="${AISTACK_NODEJS_BIN_PATH}:${PATH}" "$command" "$@"
+            fi
+            ;;
+        nvm)
+            if ! check_requirements "nodejs"; then echo " -- ERROR : nodejs missing, launch aistack init"; exit 1; fi;
+            if [ "$AISTACK_INTERNAL_NVM_AVAILABLE" = "true" ]; then
+                "$command" "$@"
+            fi
+            ;;
+        pip|pipx|uv)
+            if ! check_requirements "python"; then echo " -- ERROR : python missing, launch aistack init"; exit 1; fi;     
+            if [ "$AISTACK_INTERNAL_PYTHON_RUNTIME_AVAILABLE" = "true" ]; then
+                PATH="${AISTACK_PYTHON_BIN_PATH}:${PATH}" "$command" "$@"
+            fi
+            ;;
+        npm-config)
+            echo "WARN : COMMAND CHANGE : use $0 npm config set <key> <value>"
+            # if ! check_requirements "nodejs"; then echo " -- ERROR : nodejs missing, launch aistack init"; exit 1; fi;
+            # local sub_command="$1"
+            # shift
+            # case "$sub_command" in
+            #     set)
+            #         local key="$1"
+            #         shift
+            #         local value="$1"
+            #         shift
+            #         if [ -z "$key" ]; then
+            #             echo " -- ERROR : Missing key for npm-config set"
+            #             usage
+            #             exit 1
+            #         fi
+            #         echo "Setting npm config: $key = $value"
+            #         PATH="${AISTACK_NODEJS_BIN_PATH}:${PATH}" npm config set "$key" "$value" -g
+            #         ;;
+            #     *)
+            #         echo "Error: Unknown command $sub_command for npm-config"
+            #         usage
+            #         exit 1
+            #         ;;
+            # esac
             ;;
         app)
             local sub_command="$1"
